---
version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    ports: ['9200:9200']
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks: ['stack']
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    ports: ['5601:5601']
    networks: ['stack']
    links: ['elasticsearch']
    depends_on: ['elasticsearch']

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.5.1
    ports: ['8200:8200']
    networks: ['stack']
    links: ['elasticsearch']
    depends_on: ['elasticsearch']
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]

  foodbankhero:
    hostname: foodbankhero
    container_name: foodbankhero
    build:
      context: foodbankhero/
    ports: ['127.0.0.1:5000:5000']
    networks: ['stack']
    links: ['elasticsearch', 'apm-server']
    depends_on: ['elasticsearch', 'apm-server']
    healthcheck:
      test: ["CMD", "curl", "--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://foodbankhero:5000/"]
      interval: 500ms
      retries: 10
    # environment:
      # - FLASK_DEBUG=1
    volumes:
      - ./foodbankhero:/app

networks:
  stack: {}

volumes:
  esdata:
    driver: local
  app:
    driver: local
